services:
  goshare_migrate:
    depends_on:
      - postgres
    build:
      context: ${CWD}
      dockerfile: ${DOCKERFILE}
      args:
        GO_VERSION: ${GO_VERSION}
    entrypoint: /app/bin/migration
    image: ghcr.io/sonalys/goshare:latest
    container_name: goshare_migrate
  
  goshare:
    depends_on:
      - jaeger
      - goshare_migrate
      - postgres
    build:
      context: ${CWD}
      dockerfile: ${DOCKERFILE}
      args:
        GO_VERSION: ${GO_VERSION}
    entrypoint: "/app/bin/server"
    image: ghcr.io/sonalys/goshare:latest
    container_name: goshare
    ports:
      - "8080:8080"

  goshare_debug:
    depends_on:
      - jaeger
      - goshare_migrate
      - postgres
    build:
      context: ${CWD}
      dockerfile: ${DOCKERFILE}
      args:
        GO_VERSION: ${GO_VERSION}
    entrypoint: ["dlv", "exec", "/app/bin/server", "--headless=true", "--listen=:2345", "--api-version=2", "--accept-multiclient"]
    image: ghcr.io/sonalys/goshare:latest
    container_name: goshare_debug
    ports:
      - "8080:8080"
      - "2345:2345"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./.config/grafana/datasources:/etc/grafana/provisioning/datasources:Z

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "6831:6831/udp" # UDP port for receiving traces
      - "16686:16686" # Web UI
      - "4317:4317" # otlp grpc
      - "4318:4318" # otlp http
    volumes:
      - jaeger-data:/data

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: goshare
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./.config/loki/config.yaml:/etc/loki/config.yaml:Z

  promtail:
    image: grafana/promtail:latest
    command: -config.file=/etc/promtail/config.yaml -stdin
    container_name: promtail
    stdin_open: true
    volumes:
      - ./.config/promtail/config.yaml:/etc/promtail/config.yaml:Z

volumes:
  grafana-data: {}
  postgres-data: {}
  jaeger-data: {}