// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc application.29.0
// source: ledgers.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/sonalys/goshare/internal/domain"
)

const countLedgerUsers = `-- name: CountLedgerUsers :one
SELECT COUNT(*) FROM ledgers WHERE id = $1
`

func (q *Queries) CountLedgerUsers(ctx context.Context, id domain.ID) (int64, error) {
	row := q.db.QueryRow(ctx, countLedgerUsers, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserLedgers = `-- name: CountUserLedgers :one
SELECT COUNT(*) FROM ledgers WHERE created_by = $1
`

func (q *Queries) CountUserLedgers(ctx context.Context, createdBy domain.ID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserLedgers, createdBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLedger = `-- name: CreateLedger :exec
INSERT INTO ledgers (id,name,created_at,created_by) VALUES ($1,$2,$3,$4)
`

type CreateLedgerParams struct {
	ID        domain.ID
	Name      string
	CreatedAt pgtype.Timestamptz
	CreatedBy domain.ID
}

func (q *Queries) CreateLedger(ctx context.Context, arg CreateLedgerParams) error {
	_, err := q.db.Exec(ctx, createLedger,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}

const createLedgerMember = `-- name: CreateLedgerMember :exec
INSERT INTO ledger_members (ledger_id,user_id,created_at,created_by,balance) 
VALUES ($1,$2,$3,$4,$5) 
ON CONFLICT(user_id) 
DO UPDATE
SET balance = EXCLUDED.balance
`

type CreateLedgerMemberParams struct {
	LedgerID  domain.ID
	UserID    domain.ID
	CreatedAt pgtype.Timestamptz
	CreatedBy domain.ID
	Balance   int32
}

func (q *Queries) CreateLedgerMember(ctx context.Context, arg CreateLedgerMemberParams) error {
	_, err := q.db.Exec(ctx, createLedgerMember,
		arg.LedgerID,
		arg.UserID,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.Balance,
	)
	return err
}

const deleteMembersNotIn = `-- name: DeleteMembersNotIn :exec
DELETE FROM ledger_members WHERE user_id NOT IN (SELECT UNNEST($1::uuid[]))
`

func (q *Queries) DeleteMembersNotIn(ctx context.Context, dollar_1 []domain.ID) error {
	_, err := q.db.Exec(ctx, deleteMembersNotIn, dollar_1)
	return err
}

const getLedgerById = `-- name: GetLedgerById :one
SELECT id, name, created_at, created_by FROM ledgers WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetLedgerById(ctx context.Context, id domain.ID) (Ledger, error) {
	row := q.db.QueryRow(ctx, getLedgerById, id)
	var i Ledger
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getLedgerMembers = `-- name: GetLedgerMembers :many
SELECT user_id, ledger_id, created_at, created_by, balance FROM ledger_members WHERE ledger_id = $1
`

func (q *Queries) GetLedgerMembers(ctx context.Context, ledgerID domain.ID) ([]LedgerMember, error) {
	rows, err := q.db.Query(ctx, getLedgerMembers, ledgerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerMember
	for rows.Next() {
		var i LedgerMember
		if err := rows.Scan(
			&i.UserID,
			&i.LedgerID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserLedgers = `-- name: GetUserLedgers :many
SELECT DISTINCT ledgers.id, ledgers.name, ledgers.created_at, ledgers.created_by
FROM ledgers
LEFT JOIN ledger_members 
  ON ledgers.id = ledger_members.ledger_id
WHERE ledgers.created_by = $1
   OR ledger_members.user_id = $1
ORDER BY ledgers.created_at DESC
`

func (q *Queries) GetUserLedgers(ctx context.Context, createdBy domain.ID) ([]Ledger, error) {
	rows, err := q.db.Query(ctx, getUserLedgers, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ledger
	for rows.Next() {
		var i Ledger
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLedgerForUpdate = `-- name: LockLedgerForUpdate :exec
SELECT id, name, created_at, created_by FROM ledgers WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockLedgerForUpdate(ctx context.Context, id domain.ID) error {
	_, err := q.db.Exec(ctx, lockLedgerForUpdate, id)
	return err
}

const lockUserForUpdate = `-- name: LockUserForUpdate :exec
SELECT id, first_name, last_name, email, password_hash, created_at, ledger_count FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockUserForUpdate(ctx context.Context, id domain.ID) error {
	_, err := q.db.Exec(ctx, lockUserForUpdate, id)
	return err
}

const removeUserFromLedger = `-- name: RemoveUserFromLedger :exec
DELETE FROM ledger_members WHERE user_id = $1
`

func (q *Queries) RemoveUserFromLedger(ctx context.Context, userID domain.ID) error {
	_, err := q.db.Exec(ctx, removeUserFromLedger, userID)
	return err
}

const updateLedger = `-- name: UpdateLedger :many
UPDATE ledgers SET name = $1 WHERE id = $2 RETURNING id
`

type UpdateLedgerParams struct {
	Name string
	ID   domain.ID
}

func (q *Queries) UpdateLedger(ctx context.Context, arg UpdateLedgerParams) ([]domain.ID, error) {
	rows, err := q.db.Query(ctx, updateLedger, arg.Name, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []domain.ID
	for rows.Next() {
		var id domain.ID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
