ignore:
  - internal/application/pkg/**
  - **/*.gen.go
  - cmd/**
coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 0.5%
    patch:
      default:
        target: 80%