version: '3'

env:
  CWD: "{{ .USER_WORKING_DIR }}"
  DOCKERFILE: ./dockerfile
  COMPOSE_FILE: .config/deployment/local/compose.yml
  GO_VERSION: 1.24
  VERSION: 0.1.0
  CGO_ENABLED: 0
  POSTGRES_CONN: postgresql://user:password@postgres:5432/goshare?sslmode=disable
  JAEGER_CONN: jaeger:4317

tasks:
  build-server:
    cmd: go build -ldflags "-extldflags '-static' -X main.version=$VERSION" -o ./bin/server ./cmd/server
    generates:
      - bin/server

  build-migration:
    cmd: go build -gcflags "all=-N -l" -a -ldflags "-extldflags '-static' -X main.version=$VERSION" -o ./bin/migration ./cmd/migration
    generates:
      - bin/migration

  tidy:
    cmd: >
      go mod tidy
      $(cd .tools/ogen; go mod tidy)
      $(cd .tools/sqlc; go mod tidy)
      $(cd .tools/mockery; go mod tidy)

  upgrade_tools:
    cmd: >
      $(cd .tools/ogen; go get -tool github.com/ogen-go/ogen/cmd/ogen@latest)
      $(cd .tools/sqlc; go get -tool github.com/sqlc-dev/sqlc/cmd/sqlc@latest)
      $(cd .tools/mockery; go get -tool github.com/vektra/mockery/v3@latest)

  build:
    deps: [build-server,build-migration]

  dev:
    env:
      POSTGRES_CONN: postgresql://user:password@localhost:5432/goshare?sslmode=disable
      JAEGER_CONN: localhost:4317
    cmd: go run ./cmd/server/... | docker compose -f {{ .COMPOSE_FILE }} run --rm -T promtail

  migrate:
    env:
      POSTGRES_CONN: postgresql://user:password@localhost:5432/goshare?sslmode=disable
      JAEGER_CONN: localhost:4317
    cmd: go run ./cmd/migration/...

  generate-sql:
    cmd: go tool -modfile=.tools/sqlc/go.mod sqlc -f .config/.sqlc.yaml generate

  generate-openapi:
    cmd: go tool -modfile=.tools/ogen/go.mod ogen -package handlers --target cmd/server/handlers --clean cmd/server/spec/root.yaml
    sources:
      - cmd/server/spec/root.yaml

  generate-mocks:
    cmd: >
      rm -rf mocks;
      go tool -modfile=.tools/mockery/go.mod mockery --config .config/.mockery.yaml

  compose-server:
    cmd: docker compose -f {{ .COMPOSE_FILE }} up -d --build goshare && docker compose -f {{ .COMPOSE_FILE }} logs -f goshare_migrate goshare

  compose-down-server:
    cmd: docker compose -f {{ .COMPOSE_FILE }} down goshare

  compose:
    cmd: docker compose -f {{ .COMPOSE_FILE }} up -d --build && docker compose -f {{ .COMPOSE_FILE }} logs -f goshare_migrate goshare

  compose-down:
    args:
      services
    cmd: docker compose -f {{ .COMPOSE_FILE }} down -v

  compose-db:
    cmd: docker compose -f {{ .COMPOSE_FILE }} up -d postgres

  compose-down-infra:
    cmd: docker compose -f {{ .COMPOSE_FILE }} down -v postgres jaeger promtail loki grafana

  compose-infra:
    cmd: docker compose -f {{ .COMPOSE_FILE }} up -d postgres jaeger promtail loki grafana

  enter-db:
    cmd: docker exec -it postgres psql -U user goshare

  debug-server:
    cmd: dlv debug cmd/server --headless --listen=:2345 --api-version=2 --accept-multiclient
    sources:
      - ./**/*.go
      - go.mod
      - go.sum
    generates:
      - bin/server
