openapi: "3.0.0"
info:
  version: 1.0.0
  title: Rest API for GoShare

servers:
  - url: http://localhost:8080/api/v1
    description: Development server

paths:
  /healthcheck:
    get:
      operationId: GetHealthcheck
      summary: Healthcheck
      description: Check if the service is healthy
      responses:
        default:
          $ref: "#/components/responses/ErrorResponse"
        '200':
          description: Service is healthy

  /authentication/whoami:
    get:
      operationId: GetIdentity
      description: returns current information on the authenticated entity
      security:
        - cookieAuth: []
      responses:
        default:
          $ref: "#/components/responses/ErrorResponse"
        '200':
          description: Caller is authenticated and the data is successfully retrieved
          content:
            application/json:
              schema:
                type: object
                required:
                  - user_id
                  - email
                properties:
                  email:
                    type: string
                    format: email
                    description: User's email address
                    example: "john.doe@example.com"
                  user_id:
                    type: string
                    format: uuid

  /authentication/login:
    post:
      operationId: Login
      description: Authenticate as the specified identity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                  example: "john.doe@example.com"
                password:
                  type: string
                  format: password
                  description: User's password
                  example: "P@ssw0rd"
      responses:
        default:
          $ref: "#/components/responses/ErrorResponse"
        '200':
          description: Successfully authenticated
          headers:
            Set-Cookie:
              schema:
                type: string
                example: SESSIONID=abcde12345; Path=/; HttpOnly

  /users:
    post:
      operationId: RegisterUser
      description: Registers a new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - first_name
                - last_name
                - email
                - password
              properties:
                first_name:
                  type: string
                  description: User's first name
                  example: "John"
                last_name:
                  type: string
                  description: User's last name
                  example: "Doe"
                email:
                  type: string
                  format: email
                  description: User's email address
                  example: "john.doe@example.com"
                password:
                  type: string
                  format: password
                  description: User's password
                  example: "P@ssw0rd"
      responses:
        default:
          $ref: "#/components/responses/ErrorResponse"
        '200':
          description: User was registered
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                properties:
                  id:
                    type: string
                    format: uuid

  /ledgers:
    get:
      operationId: ListLedgers
      description: Lists all ledgers
      security:
        - cookieAuth: []
      responses:
        default:
          $ref: "#/components/responses/ErrorResponse"
        '200':
          description: List of ledgers
          content:
            application/json:
              schema:
                type: object
                required:
                  - ledgers
                properties:
                  ledgers:
                    type: array
                    items:
                      $ref: "#/components/schemas/Ledger"
    post:
      operationId: CreateLedger
      description: Creates a new ledger
      security:
        - cookieAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  description: Ledger's name
                  example: "My Ledger"
      responses:
        default:
          $ref: "#/components/responses/ErrorResponse"
        '200':
          description: Ledger was created
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                properties:
                  id:
                    type: string
                    format: uuid

  /ledgers/{ledgerID}/expenses:
    post:
      operationId: CreateExpense
      description: Creates a new expense
      security:
        - cookieAuth: []
      parameters:
        - name: ledgerID
          in: path
          required: true
          description: Ledger ID
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - amount
                - name
                - expense_date
                - user_balances
              properties:
                amount:
                  type: integer
                  format: int32
                  description: Expense amount
                  example: 10000
                category_id:
                  type: string
                  format: uuid
                  description: Category ID
                  example: "123e4567-e89b-12d3-a456-426614174000"
                name:
                  type: string
                  description: Expense name
                  example: "Dinner"
                expense_date:
                  type: string
                  format: date-time
                  description: Date and time the expense was made
                  example: "2020-01-01T00:00:00Z"
                user_balances:
                  type: array
                  items:
                    $ref: "#/components/schemas/ExpenseUserBalance"
      responses:
        default:
          $ref: "#/components/responses/ErrorResponse"
        '200':
          description: Expense was created
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                properties:
                  id:
                    type: string
                    format: uuid

  /ledgers/{ledgerID}/balances:
    get:
      operationId: ListLedgerBalances
      description: Lists all ledger balances
      security:
        - cookieAuth: []
      parameters:
        - name: ledgerID
          in: path
          required: true
          description: Ledger ID
          schema:
            type: string
            format: uuid
      responses:
        default:
          $ref: "#/components/responses/ErrorResponse"
        '200':
          description: List of ledger balances
          content:
            application/json:
              schema:
                type: object
                required:
                  - balances
                properties:
                  balances:
                    type: array
                    items:
                      $ref: "#/components/schemas/LedgerParticipantBalance"

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: SESSIONID
  responses:
    ErrorResponse:
      description: An error has occurred
      content:
        application/json:
          schema:
            type: object
            required:
              - trace_id
              - errors
              - url
            properties:
              url:
                type: string
                description: URL of the failed request
                example: "/v1/users"
              trace_id:
                type: string
                format: uuid
                description: Unique identifier for the error instance
                example: "b6b7b3b0-1b4d-4f4b-8b3e-1b4d4f4b8b3e"
              errors:
                type: array
                minItems: 1
                items:
                  $ref: "#/components/schemas/Error"
  schemas:
    ExpenseUserBalance:
      type: object
      required:
        - user_id
        - balance
      properties:
        user_id:
          type: string
          format: uuid
        balance:
          type: integer
          format: int32
    LedgerParticipantBalance:
      type: object
      required:
        - user_id
        - balance
      properties:
        user_id:
          type: string
          format: uuid
        balance:
          type: integer
          format: int32
    Ledger:
      type: object
      required:
        - id
        - name
        - created_at
        - created_by
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          description: Ledger's name
          example: "My Ledger"
        created_at:
          type: string
          format: date-time
          description: Date and time the ledger was created
          example: "2020-01-01T00:00:00Z"
        created_by:
          type: string
          format: uuid
          description: User ID of the creator
          example: "123e4567-e89b-12d3-a456-426614174000"
    ErrorMetadata:
      type: object
      properties:
        field:
          type: string
          example: "name"
    Error:
      type: object
      required:
        - message
        - code
      properties:
        code:
          type: string
          enum:
            - "not_found"
            - "required_header"
            - "required_parameter"
            - "invalid_parameter"
            - "internal_error"
            - "required_body"
            - "invalid_field"
            - "required_field"
            - "email_password_mismatch"
            - "forbidden"
            - "unauthorized"
        message:
          type: string
          description: Human readable error message
          example: "Missing parameter 'name'"
        metadata:
          $ref: "#/components/schemas/ErrorMetadata"