openapi: "3.0.0"
info:
  version: 1.0.0
  title: Rest API for GoShare

servers:
  - url: http://localhost:8080/api/v1
    description: Development server

paths:
  /healthcheck:
    get:
      operationId: GetHealthcheck
      summary: Healthcheck
      description: Check if the service is healthy
      responses:
        default:
          $ref: "#/components/responses/ErrorResponse"
        '200':
          description: Service is healthy

  /authentication/login:
    post:
      operationId: Login
      description: Authenticate as the specified identity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                  example: "john.doe@example.com"
                password:
                  type: string
                  format: password
                  description: User's password
                  example: "P@ssw0rd"
      responses:
        default:
          $ref: "#/components/responses/ErrorResponse"
        '200':
          description: Successfully authenticated
          headers:
            Set-Cookie:
              schema:
                type: string
                example: SESSIONID=abcde12345; Path=/; HttpOnly

  /users:
    post:
      operationId: RegisterUser
      description: Registers a new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - first_name
                - last_name
                - email
                - password
              properties:
                first_name:
                  type: string
                  description: User's first name
                  example: "John"
                last_name:
                  type: string
                  description: User's last name
                  example: "Doe"
                email:
                  type: string
                  format: email
                  description: User's email address
                  example: "john.doe@example.com"
                password:
                  type: string
                  format: password
                  description: User's password
                  example: "P@ssw0rd"
      responses:
        default:
          $ref: "#/components/responses/ErrorResponse"
        '200':
          description: User was registered
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                properties:
                  id:
                    type: string
                    format: uuid

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: SESSIONID
  responses:
    ErrorResponse:
      description: An error has occurred
      content:
        application/json:
          schema:
            type: object
            required:
              - trace_id
              - errors
              - url
            properties:
              url:
                type: string
                description: URL of the failed request
                example: "/v1/users"
              trace_id:
                type: string
                format: uuid
                description: Unique identifier for the error instance
                example: "b6b7b3b0-1b4d-4f4b-8b3e-1b4d4f4b8b3e"
              errors:
                type: array
                minItems: 1
                items:
                  $ref: "#/components/schemas/Error"
  schemas:
    ErrorMetadata:
      type: object
      properties:
        field:
          type: string
          example: "name"
    Error:
      type: object
      required:
        - message
        - code
      properties:
        code:
          type: string
          enum:
            - "not_found"
            - "required_header"
            - "required_parameter"
            - "invalid_parameter"
            - "internal_error"
            - "required_body"
            - "invalid_field"
            - "required_field"
            - "email_password_mismatch"
        message:
          type: string
          description: Human readable error message
          example: "Missing parameter 'name'"
        metadata:
          $ref: "#/components/schemas/ErrorMetadata"