// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Participant struct {
	ID           pgtype.UUID
	FirstName    string
	LastName     string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
}
