apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    url: http://jaeger:16686
    readOnly: false
    isDefault: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'Loki'
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
        filterByTraceID: true
        filterBySpanID: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false