// Code generated by ogen, DO NOT EDIT.

package handlers

// OperationName is the ogen operation name
type OperationName = string

const (
	AddLedgerParticipantOperation   OperationName = "AddLedgerParticipant"
	CreateExpenseOperation          OperationName = "CreateExpense"
	CreateLedgerOperation           OperationName = "CreateLedger"
	GetExpenseOperation             OperationName = "GetExpense"
	GetHealthcheckOperation         OperationName = "GetHealthcheck"
	GetIdentityOperation            OperationName = "GetIdentity"
	ListLedgerParticipantsOperation OperationName = "ListLedgerParticipants"
	ListLedgersOperation            OperationName = "ListLedgers"
	LoginOperation                  OperationName = "Login"
	RegisterUserOperation           OperationName = "RegisterUser"
)
