// Code generated by ogen, DO NOT EDIT.

package handlers

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddLedgerParticipant implements AddLedgerParticipant operation.
//
// Adds a new member to the Ledger.
//
// POST /ledgers/{ledgerID}/participants
func (UnimplementedHandler) AddLedgerParticipant(ctx context.Context, req *AddLedgerParticipantReq, params AddLedgerParticipantParams) error {
	return ht.ErrNotImplemented
}

// CreateExpense implements CreateExpense operation.
//
// Creates a new expense record.
//
// POST /ledgers/{ledgerID}/expenses
func (UnimplementedHandler) CreateExpense(ctx context.Context, req *Expense, params CreateExpenseParams) (r *CreateExpenseOK, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateLedger implements CreateLedger operation.
//
// Creates a new ledger. A user can have a maximum of 5 ledgers.
//
// POST /ledgers
func (UnimplementedHandler) CreateLedger(ctx context.Context, req *CreateLedgerReq) (r *CreateLedgerOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetExpense implements GetExpense operation.
//
// Retrieves an expense record.
//
// GET /ledgers/{ledgerID}/expenses/{expenseID}
func (UnimplementedHandler) GetExpense(ctx context.Context, params GetExpenseParams) (r *Expense, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealthcheck implements GetHealthcheck operation.
//
// Check if the service is healthy.
//
// GET /healthcheck
func (UnimplementedHandler) GetHealthcheck(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// GetIdentity implements GetIdentity operation.
//
// Returns current information on the authenticated entity.
//
// GET /authentication/whoami
func (UnimplementedHandler) GetIdentity(ctx context.Context) (r *GetIdentityOK, _ error) {
	return r, ht.ErrNotImplemented
}

// ListLedgerParticipants implements ListLedgerParticipants operation.
//
// Lists all ledger participants and their balances.
//
// GET /ledgers/{ledgerID}/participants
func (UnimplementedHandler) ListLedgerParticipants(ctx context.Context, params ListLedgerParticipantsParams) (r *ListLedgerParticipantsOK, _ error) {
	return r, ht.ErrNotImplemented
}

// ListLedgers implements ListLedgers operation.
//
// Lists all ledgers.
//
// GET /ledgers
func (UnimplementedHandler) ListLedgers(ctx context.Context) (r *ListLedgersOK, _ error) {
	return r, ht.ErrNotImplemented
}

// Login implements Login operation.
//
// Authenticate as the specified identity.
//
// POST /authentication/login
func (UnimplementedHandler) Login(ctx context.Context, req *LoginReq) (r *LoginOK, _ error) {
	return r, ht.ErrNotImplemented
}

// RegisterUser implements RegisterUser operation.
//
// Registers a new user.
//
// POST /users
func (UnimplementedHandler) RegisterUser(ctx context.Context, req *RegisterUserReq) (r *RegisterUserOK, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorResponseStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorResponseStatusCode) {
	r = new(ErrorResponseStatusCode)
	return r
}
