// Code generated by ogen, DO NOT EDIT.

package handlers

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddLedgerMember implements AddLedgerMember operation.
//
// Adds a new member to the Ledger.
//
// POST /ledgers/{ledgerID}/members
func (UnimplementedHandler) AddLedgerMember(ctx context.Context, req *AddLedgerMemberReq, params AddLedgerMemberParams) error {
	return ht.ErrNotImplemented
}

// CreateExpense implements CreateExpense operation.
//
// Creates a new expense.
//
// POST /ledgers/{ledgerID}/expenses
func (UnimplementedHandler) CreateExpense(ctx context.Context, req *CreateExpenseReq, params CreateExpenseParams) (r *CreateExpenseOK, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateLedger implements CreateLedger operation.
//
// Creates a new ledger. A user can have a maximum of 5 ledgers.
//
// POST /ledgers
func (UnimplementedHandler) CreateLedger(ctx context.Context, req *CreateLedgerReq) (r *CreateLedgerOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealthcheck implements GetHealthcheck operation.
//
// Check if the service is healthy.
//
// GET /healthcheck
func (UnimplementedHandler) GetHealthcheck(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// GetIdentity implements GetIdentity operation.
//
// Returns current information on the authenticated entity.
//
// GET /authentication/whoami
func (UnimplementedHandler) GetIdentity(ctx context.Context) (r *GetIdentityOK, _ error) {
	return r, ht.ErrNotImplemented
}

// ListLedgerBalances implements ListLedgerBalances operation.
//
// Lists all ledger balances.
//
// GET /ledgers/{ledgerID}/balances
func (UnimplementedHandler) ListLedgerBalances(ctx context.Context, params ListLedgerBalancesParams) (r *ListLedgerBalancesOK, _ error) {
	return r, ht.ErrNotImplemented
}

// ListLedgerExpenses implements ListLedgerExpenses operation.
//
// Lists the expenses of the Ledger.
//
// GET /ledgers/{ledgerID}/expenses
func (UnimplementedHandler) ListLedgerExpenses(ctx context.Context, params ListLedgerExpensesParams) (r *ListLedgerExpensesOK, _ error) {
	return r, ht.ErrNotImplemented
}

// ListLedgers implements ListLedgers operation.
//
// Lists all ledgers.
//
// GET /ledgers
func (UnimplementedHandler) ListLedgers(ctx context.Context) (r *ListLedgersOK, _ error) {
	return r, ht.ErrNotImplemented
}

// Login implements Login operation.
//
// Authenticate as the specified identity.
//
// POST /authentication/login
func (UnimplementedHandler) Login(ctx context.Context, req *LoginReq) (r *LoginOK, _ error) {
	return r, ht.ErrNotImplemented
}

// RegisterUser implements RegisterUser operation.
//
// Registers a new user.
//
// POST /users
func (UnimplementedHandler) RegisterUser(ctx context.Context, req *RegisterUserReq) (r *RegisterUserOK, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorResponseStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorResponseStatusCode) {
	r = new(ErrorResponseStatusCode)
	return r
}
