// Code generated by ogen, DO NOT EDIT.

package server

// OperationName is the ogen operation name
type OperationName = string

const (
	AuthenticationLoginOperation       OperationName = "AuthenticationLogin"
	AuthenticationWhoAmIOperation      OperationName = "AuthenticationWhoAmI"
	HealthcheckOperation               OperationName = "Healthcheck"
	LedgerCreateOperation              OperationName = "LedgerCreate"
	LedgerExpenseCreateOperation       OperationName = "LedgerExpenseCreate"
	LedgerExpenseGetOperation          OperationName = "LedgerExpenseGet"
	LedgerExpenseListOperation         OperationName = "LedgerExpenseList"
	LedgerExpenseRecordCreateOperation OperationName = "LedgerExpenseRecordCreate"
	LedgerExpenseRecordDeleteOperation OperationName = "LedgerExpenseRecordDelete"
	LedgerListOperation                OperationName = "LedgerList"
	LedgerMemberAddOperation           OperationName = "LedgerMemberAdd"
	LedgerMemberListOperation          OperationName = "LedgerMemberList"
	UserRegisterOperation              OperationName = "UserRegister"
)
