version: "2"
linters:
  default: all
  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true
  exclusions:
    generated: lax
    paths:
      - internal/mocks
      - ".*\\.gen\\.go$"
    rules:
      - path: '_test.go'
        linters:
          - bodyclose
      - path: 'repositories'
        linters:
          - paralleltest
  disable:
    - wsl
    - wsl_v5
    - mnd
    - noinlineerr
    - depguard
    - exhaustruct
    - varnamelen
    - nonamedreturns
    - nakedret
    - wrapcheck
    - lll
    - thelper
    - godox
    - exhaustive
    - err113
    - ireturn
    - gochecknoglobals
    - cyclop
    - maintidx
    - funlen
    - contextcheck