dir: 'mocks/{{ .SrcPackagePath | trimPrefix "github.com/sonalys/goshare" | replaceAll "internal" "internal_" }}'
filename: mocks.gen.go
force-file-write: false
formatter: goimports
log-level: info
structname: '{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}mock'
template: matryer
packages:
  github.com/sonalys/goshare/internal/infrastructure/postgres:
  github.com/sonalys/goshare/internal:
    config:
      all: true
      recursive: true