dir: 'internal/mocks/{{ .SrcPackagePath | trimPrefix "github.com/sonalys/goshare/internal" }}mock'
filename: mocks.gen.go
force-file-write: false
formatter: goimports
log-level: info
structname: '{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}mock'
template: matryer
packages:
  github.com/sonalys/goshare/internal:
    config:
      all: true
      recursive: true
      exclude-subpkg-regex:
        - infrastructure