version: "2"
sql:
  - engine: "postgresql"
    queries: "../internal/infrastructure/postgres/queries"
    schema: "../internal/infrastructure/postgres/migrations"
    gen:
      go:
        package: "sqlc"
        out: "../internal/infrastructure/postgres/sqlc"
        sql_package: "pgx/v5"