name: Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: sqlc check
        run: |
          task diff-sqlc
          task vet-sql

      - name: mockery check
        run: task diff-mockery