name: Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - uses: golangci/golangci-lint-action@v8
        with:
          args: -c .config/.golangci.yaml
      - uses: arduino/setup-task@v2

      - name: sqlc check
        run: |
          task diff-sqlc
          task vet-sql

      - name: mockery check
        run: task diff-mockery