name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
      - uses: actions/setup-go@v5
        with:
          cache-dependency-path: "**/*.sum"

      - name: Test
        run: |
          task download
          task test-coverage || true
          task junit-report

      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./report.xml

      - uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: ./report.xml