name: Unit tests

on:
  push:
    paths:
      - ".github/workflows/test.yml"
      - "taskfile.yml"
      - "**/*.go"

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 1s
          --health-timeout 1s
          --health-retries 10
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
      - uses: actions/setup-go@v5
        with:
          cache-dependency-path: "**/*.sum"

      - name: Test
        env:
          POSTGRES_CONN_STR: postgresql://postgres:postgres@localhost:5432/postgres
        run: |
          task download
          task test-coverage;
          task junit-report

      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./report.xml

      - uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: ./report.xml